cargo-features = ["edition"]

[package]
name = "zircond"
version = "0.1.0"
authors = ["splittydev <splittydev@protonmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0"
toml = "0.4"